name: Auto-merge user-owned changes

on:
  push:
    branches:
      - stage

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - run: ./can-auto-merge.sh
      env:
        PREV_HASH: ${{ github.event.before }}
        CURR_HASH: ${{ github.sha }}
        GITHUB_ID: ${{ github.actor }}

    - if: ${{ success() }}
      run: |
        git checkout main
        git merge --no-ff ${{ github.ref }}
        git push origin main
