name: Auto-merge user-owned changes

on:
  push:
    branches-ignore:
      - 'main'

permissions:
  contents: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - run: |
        nix-env -i jq -f '<nixpkgs>'

    - run: |
        git fetch origin main
        export PREV_HASH=$(git rev-parse origin/main)
        ./check.sh && ./can-auto-merge.sh
      env:
        CURR_HASH: ${{ github.sha }}
        GITHUB_ID: ${{ github.actor_id }}

    - if: ${{ success() }}
      run: |
        git checkout main
        git merge ${{ github.ref }}
        git push origin main
        git push origin --delete ${{ github.ref }}
