name: Check for valid NixOS configuration

on:
  pull_request:
    branches:
      - 'main'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - uses: cachix/install-nix-action@v31
    - run: ./check.sh
