name: Run check & attempt auto-merge

on:
  push:
    branches-ignore:
      - 'main'

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
    - run: ./check.sh

  auto-merge:
    needs: check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ssh-key: ${{ secrets.GHA_DEPLOY_KEY }}

    - uses: cachix/install-nix-action@v31

    - id: can-auto-merge
      run: |
        git fetch origin main
        PREV_HASH=$(git rev-parse origin/main) ./can-auto-merge.sh
      env:
        CURR_HASH: ${{ github.sha }}
        GITHUB_ID: ${{ github.actor_id }}
      continue-on-error: true

    - if: steps.can-auto-merge.outcome == 'success'
      run: |
        git checkout main
        git merge ${{ github.ref }}
        git push origin main
        git push origin --delete ${{ github.ref }}
